export const mockCustomers = [
  {
    id: "c-001",
    name: "华东机电",
    source: "企业微信咨询",
    stage: "new",
    owner: "李销售",
    need: "想要一套支持产品报价和客户跟进的轻量系统。",
    quotedAmount: 32000,
    dealAmount: 0,
    receivableAmount: 0,
    paymentStatus: "未成交",
    lastFollowUpAt: "2026-05-26 15:20",
    risk: "报价后 2 天未跟进",
  },
  {
    id: "c-002",
    name: "星河建材",
    source: "老客户转介绍",
    stage: "won",
    owner: "王销售",
    need: "需要把合同、送货单和回款提醒统一管理。",
    quotedAmount: 58000,
    dealAmount: 58000,
    receivableAmount: 18000,
    paymentStatus: "部分回款",
    lastFollowUpAt: "2026-05-27 09:10",
    risk: "尾款 7 天后到期",
  },
  {
    id: "c-003",
    name: "鼎盛五金",
    source: "官网表单",
    stage: "quoted",
    owner: "陈销售",
    need: "客户希望销售能快速生成标准报价说明。",
    quotedAmount: 26000,
    dealAmount: 0,
    receivableAmount: 0,
    paymentStatus: "未成交",
    lastFollowUpAt: "2026-05-25 18:40",
    risk: "报价后 3 天未跟进",
  },
  {
    id: "c-004",
    name: "北辰包装",
    source: "线下展会",
    stage: "follow_up",
    owner: "赵销售",
    need: "想先试用客户台账和老板日报。",
    quotedAmount: 12000,
    dealAmount: 0,
    receivableAmount: 0,
    paymentStatus: "未成交",
    lastFollowUpAt: "2026-05-27 11:05",
    risk: "",
  },
  {
    id: "c-005",
    name: "嘉禾食品",
    source: "朋友介绍",
    stage: "receivable",
    owner: "王销售",
    need: "已经签约，需要提醒销售跟进发票和回款。",
    quotedAmount: 45000,
    dealAmount: 45000,
    receivableAmount: 45000,
    paymentStatus: "待回款",
    lastFollowUpAt: "2026-05-27 10:30",
    risk: "首款今天到期",
  },
];

export const dashboardActionItems = [
  "优先跟进华东机电和鼎盛五金，两个客户都处在报价后未跟进状态。",
  "提醒王销售处理星河建材尾款，避免到期后再追。",
  "把北辰包装的试用需求整理为低价试点方案，争取本周成交。",
];

export const mockKnowledgeItems = [
  {
    id: "kb-product-light-erp",
    category: "product",
    title: "轻量进销存与报价跟进方案",
    content: "适合小型工厂、贸易公司和批发企业，包含产品资料、库存台账、报价管理、客户跟进、回款提醒和老板日报。",
    keywords: ["小型工厂", "进销存", "库存", "报价管理", "客户跟进", "微信通知"],
    updatedAt: "2026-05-27",
  },
  {
    id: "kb-pricing-30k-pilot",
    category: "pricing",
    title: "3 万以内试点报价规则",
    content: "预算 3 万以内时，建议交付知识库、AI 销售助手、报价跟进、客户台账和老板日报，试运行周期为 30 天。",
    keywords: ["3 万以内", "试点", "报价规则", "老板日报"],
    updatedAt: "2026-05-27",
  },
  {
    id: "kb-faq-wechat",
    category: "faq",
    title: "是否支持企业微信提醒",
    content: "第一阶段支持通过企业微信或钉钉机器人发送销售未跟进、回款到期和客户投诉提醒。",
    keywords: ["企业微信", "微信", "钉钉", "提醒", "通知"],
    updatedAt: "2026-05-27",
  },
  {
    id: "kb-contract-pilot",
    category: "contract",
    title: "试点项目合同边界",
    content: "试点合同建议写清客户资料数量、产品资料数量、销售账号数量、试运行周期、验收指标和后续扩展范围。",
    keywords: ["合同模板", "试点", "验收", "交付边界"],
    updatedAt: "2026-05-27",
  },
];
