export const mockCustomers = [
  {
    id: "c-001",
    name: "华东机电",
    source: "企业微信咨询",
    stage: "new",
    owner: "李销售",
    need: "想要一套支持产品报价和客户跟进的轻量系统。",
    quotedAmount: 32000,
    dealAmount: 0,
    receivableAmount: 0,
    paymentStatus: "未成交",
    lastFollowUpAt: "2026-05-26 15:20",
    risk: "报价后 2 天未跟进",
  },
  {
    id: "c-002",
    name: "星河建材",
    source: "老客户转介绍",
    stage: "won",
    owner: "王销售",
    need: "需要把合同、送货单和回款提醒统一管理。",
    quotedAmount: 58000,
    dealAmount: 58000,
    receivableAmount: 18000,
    paymentStatus: "部分回款",
    lastFollowUpAt: "2026-05-27 09:10",
    risk: "尾款 7 天后到期",
  },
  {
    id: "c-003",
    name: "鼎盛五金",
    source: "官网表单",
    stage: "quoted",
    owner: "陈销售",
    need: "客户希望销售能快速生成标准报价说明。",
    quotedAmount: 26000,
    dealAmount: 0,
    receivableAmount: 0,
    paymentStatus: "未成交",
    lastFollowUpAt: "2026-05-25 18:40",
    risk: "报价后 3 天未跟进",
  },
  {
    id: "c-004",
    name: "北辰包装",
    source: "线下展会",
    stage: "follow_up",
    owner: "赵销售",
    need: "想先试用客户台账和老板日报。",
    quotedAmount: 12000,
    dealAmount: 0,
    receivableAmount: 0,
    paymentStatus: "未成交",
    lastFollowUpAt: "2026-05-27 11:05",
    risk: "",
  },
  {
    id: "c-005",
    name: "嘉禾食品",
    source: "朋友介绍",
    stage: "receivable",
    owner: "王销售",
    need: "已经签约，需要提醒销售跟进发票和回款。",
    quotedAmount: 45000,
    dealAmount: 45000,
    receivableAmount: 45000,
    paymentStatus: "待回款",
    lastFollowUpAt: "2026-05-27 10:30",
    risk: "首款今天到期",
  },
];

export const dashboardActionItems = [
  "优先跟进华东机电和鼎盛五金，两个客户都处在报价后未跟进状态。",
  "提醒王销售处理星河建材尾款，避免到期后再追。",
  "把北辰包装的试用需求整理为低价试点方案，争取本周成交。",
];
